import os
import time
from datetime import date
repeat = "Y", "y"

time.sleep(1)

print("Welkom bij: (Het verhaal van)")

print("                                                                             ")
time.sleep(1)
print("     000       000        00              00         00              00      ")
time.sleep(1)
print("     000       000         00            00           00            00       ")
time.sleep(1)
print("     000       000          00          00             00          00        ")
time.sleep(1)
print("     0000000000000           00        00               00        00         ")
time.sleep(1)
print("     0000000000000            00      00                 00      00          ")
time.sleep(1)
print("     000       000             00    00                   00    00           ")
time.sleep(1)
print("     000       000              00  00                     00  00            ")
time.sleep(1)
print("     000       000                00                         00              ")
time.sleep(1)
print("                                                                             ")
print(" ")
time.sleep(1)
print("Er zijn meedere keuzes dus probeer alles zeker uit!")
print(" ")
time.sleep(1)
print("BELANGERIJK: De meeste vragen worden beantwoord met Y of N ( Yes or no ) gebruik hierbij altijd hoofdletters om bugs te verkomen.")
time.sleep(1)

while repeat[0] not in ("N"):
    print("Mijn naam is Alyas, vandaag ben jij verantwoordelijk voor mijn keuzes. Jij moet mij helpen om naar Nederland te komen.")
    time.sleep(1)
    print(" ")
    print(" ")
    print(" ")
    time.sleep(1)
    print("Laten we beginnen bij het begin ik woon samen met mijn man en dochter in Irak. We waren heel gelukkig, totdat er oorlog uitbrak.")
    print(" ")
    time.sleep(1)
    print("De rede dat wij willen vluchten is omdat wij een apart geloof hebben dat niet word geaccepteerd. Dus we zijn niet veilig.")
    print(" ")
    time.sleep(1)
    print("We willen zo snel mogelijk vertrekken maar het is wel belangerijk dat wij een plan maken.")
    time.sleep(1)
    print("Welke kant kunnen wij het beste op?")
    time.sleep(1)
    print("Keuzes: A: Via Turkije, B: Libanon, C: Vliegtuig ")
    time.sleep(1)
    w1v1 = input("Keuze: ")
    if w1v1 == "A":
        print("Via Turkije word het dan!")
        time.sleep(1)
        print(" ")
        time.sleep(1)
        print("Gaan we een vervoersmiddel gebruiken?")
        time.sleep(1)
        w1v2 = input("Y/N: ")
        if w1v2 == "Y":
            print("Oke dan!")
            time.sleep(1)
            print("Daar staat een vrachtwagen, ik ga hem vragen of wij mee mogen!")
            time.sleep(1)
            print(" ")
            time.sleep(1)
            print("De chauffeur zij ja en we mogen mee richting Turkije!")
            print(" ")
            time.sleep(1)
            print("De reis duurde een aantal uur maar we zijn aangekomen in Turkije.")
            print(" ")
            time.sleep(1)
            print("We zijn redelijk uitgeput en moeten ergens een tijdje rusten...")
            time.sleep(1)
        if w1v2 == "N":
            print("Dan maar te voet...")
            time.sleep(1)
            print(" ")
            time.sleep(1)
            print("Het lopen is enorm zwaar...")
            time.sleep(1)
            print(" ")
            print("Maar gelukkig konden we onderweg wat eten scooren.")
            print(" ")
            time.sleep(1)
            print("Na 15 dagen lopen zijn we aangekomen in Turkije")
            print(" ")
            time.sleep(1)
            print("We zijn uitgeput en moeten ergens een tijdje rusten...")
            time.sleep(1)

        print("We zijn op dit moment in het stadje Kalaba")
        print(" ")
        time.sleep(1)
        print("We konden hier nergens een rust plaats vinden dus zijn maar op straat gaan slapen...")
        print(" ")
        time.sleep(1)
        print("De volgende dag zijn we door gelopen naar het stadje Kırşehir, daar woont een nicht van mij dus we konden daar gelukkig een tijdje rusten.")
        print(" ")
        time.sleep(1)
        print("Na een aantal dagen te rusten wilde we weer verder, dus mijn nicht had ons afgezet bij de grens van Bulgarije.")
        print(" ")
        time.sleep(1)
        print("Gaan we vanaf hier weer een vervoersmiddel gebruiken?")
        print(" ")
        time.sleep(1)
        w1v3 = input("Y/N: ")
        if w1v3 == "Y":
            print(" ")
            print("We hebben ons laatste geld uitgegeven aan een busreis van 15 uur.")
            print(" ")
            time.sleep(1)
            print("Hiermee konden helemaal bij Praag komen! Eenmaal in Praag hebben we even uitgerust. Er was een vriendelijke motel eigenaar die ons een gratis nachtje gunde!")
            print(" ")
            time.sleep(1)
        if w1v3 == "N":
            print("Gaat lastig worden zonder vervoer... Maar gelukkig hebben we nu nog wel wat geld over.")
            print(" ")
            time.sleep(1)
            print("Ik heb het laatste geld gebruikt en we hebben kleine stukjes gelift en zijn vervolgens in Praag aangekomen")
            print(" ")
            time.sleep(1)
            print("Eenmaal in Praag hebben we even uitgerust. Er was een vriendelijke motel eigenaar die ons een gratis nachtje gunde!")
            time.sleep(1)
            break

        print("Het is vanaf Praag nog maar 850Km. Wij besloten om in Praag proberen wat geld te verdienen. We hebben hier een aantal klusjes gedaan voor verschillenende mensen!.")
        print(" ")
        time.sleep(1)
        print("We hebben genoeg geld bij elkaar gehaald om met de bus naar Duitsland te gaan!")
        print(" ")
        time.sleep(1)
        print("Vanaf Duitsland konder zo naar Amsterdam!")
        print(" ")
        time.sleep(1)
        print("De reis verliep soepeltjes en we zijn veilig op eindbestemming gekomen.")
        print(" ")
        time.sleep(1)

    if w1v1 == "B":
        print("Via Libanon")
        print(" ")
        time.sleep(1)
        print("Kijken wat ons dit gaat brengen")
        print(" ")
        time.sleep(1)
        print("Gaan we een vervoersmiddel gebruiken?")
        w2v2 = input("Y/N: ")
        if w2v2 == "Y":
            print("Een vervoersmiddel it is.")
            print(" ")
            time.sleep(1)
            print("Libanon ligt naast Syrie, dat betekent dat we daar eerst doorheen moeten.")
            print(" ")
            time.sleep(1)
            print("Gelukkig gaat er een bus vanaf Syrie naar Libanon.")
            print(" ")
            time.sleep(1)
            print("Het was 5 uur lopen maar we zijn bij de bus gekomen")
            print(" ")
            time.sleep(1)
            print("Gelukkig ging de de reis met de bus goed!")
            time.sleep(1)
        if w2v2 == "N":
            print("Geen vervoersmiddel?")
            print(" ")
            time.sleep(1)
            print("Het bespaart veel geld maar het is wel gevaarlijk.")
            print(" ")
            time.sleep(1)
            print("Nouja we hebben de fiets maar genomen richting libanon.")
            print(" ")
            time.sleep(1)
            print("Het was een gevaarlijke reis maar we hebben het gedaan.")
            print(" ")
            time.sleep(1)
            print("De reis duurde in totaal meer dan 2 dagen.")
            print(" ")
            time.sleep(1)
        
        print("Nouja de reden dat we naar Libanon zijn gegaan is zodat we met de boot kunnen.")
        print(" ")
        time.sleep(1)
        print("We hebben met een aantal andere vluchtelingen een bootje gehuurd.")
        print(" ")
        time.sleep(1)
        print("Deze zijn niet altijd even veilig maarja...")
        print(" ")
        time.sleep(1)
        print("De boot zonk de eerst 1Km door overbelasting...")
        print(" ")
        time.sleep(1)
        print("We zijn terug gezwommen naar het land en zijn een tijdje in Libanon gebleven.")
        print(" ")
        time.sleep(1)
        print(" ")
        print("Helaas! mislukt.")
        time.sleep(1)
        repeat = input("Wilt u het nog eens proberen? (Y/N): ")
    
    if w1v1 == "C":
        print("Met het vliegtuig")
        print(" ")
        time.sleep(1)
        print("Het gaat lastig worden om Nederland in te komen...")
        print(" ")
        time.sleep(1)
        print("We hebben eerst meer geld nodig.")
        print(" ")
        time.sleep(1)
        print("Hoe gaan we dat doen?")
        print(" ")
        time.sleep(1)
        print("Zullen we naar het casino?")
        time.sleep(1)
        w1v2 = input("Y/N: ")
        if w1v2 == "Y":
            print("Oke dan!")
            print(" ")
            time.sleep(1)
            print("We hebben in totaal 150 euro...")
            print(" ")
            time.sleep(1)
            print("We hebben 600 euro nodig...")
            print(" ")
            time.sleep(1)
            print("Gaan we all in op rood of op zwart?")
            time.sleep(1)
            w1v3 = input("R/Z: ")
            if w1v3 == "R":
                print("YESS!")
                print(" ")
                time.sleep(1)
                print("We hebben het verdubbeld!")
                print(" ")
                time.sleep(1)
                print("We missen nog 300 euro...")
                print("  ")
                time.sleep(1)
                print("Als we nog eens alles inzetten op rood of zwart dan kunnen we 600 euro winnen.")
                print(" ")
                time.sleep(1)
                print("Kies nog eens tussen rood of zwart.")
            if w1v3 == "Z":
                print("YESS!")
                print(" ")
                time.sleep(1)
                print("We hebben het verdubbeld!")
                print(" ")
                time.sleep(1)
                print("We missen nog 300 euro...")
                print("  ")
                time.sleep(1)
                print("Als we nog eens alles inzetten op rood of zwart dan kunnen we 600 euro winnen.")
                print(" ")
                time.sleep(1)
                print("Kies nog eens tussen rood of zwart.")
                
                w1v4 = input("R/Z: ")
                if w1v4 == "R":
                    print("HET IS GELUKT!")
                    print(" ")
                    time.sleep(1)
                    print("We kunnen met het vluigtuig!")
                    print(" ")
                    time.sleep(1)
                    print("Alles verliep soepel en we zijn naar Nederland gekomen.")

                if w1v4 == "Z":
                    print("Helaas!")
                    print(" ")
                    time.sleep(1)
                    print("We zullen een andere manier moeten zoeken...")
                    time.sleep(1)
                    repeat = input("Wilt u terug naar het begin?(Y/N): ")
        if w1v2 == "N":
            print("Helaas...")
            print(" ")
            time.sleep(1)
            print("Zonder geld geen vluigtuig...")
            print(" ")
            time.sleep(1)
            print("Wilt u het nog eens proberen?")
            repeat = input("Y/N: ")
        print("Het is je gelukt!")
        print(" ")
        time.sleep(1)
        print("Je hebt ervoor gezorgt dat deze familie terug is gekomen in Nederland.")
        print(" ")
        print(" ")
        time.sleep(1)
        print("Dit was het hele verhaal.")
        print("Al was het gelukt via 1 weg probeer dan zeker nog even de andere uit!")
        print(" ")
        time.sleep(1)
        print("Wilt u het nog eens doen?")
        repeat = input("Y/N: ")
        
                    
                    
        



            
            
            
    
    


