import os
import time
from datetime import date
repeat = "Y", "y"

time.sleep(1)

print("Welkom bij: (Het verhaal van)")

print("                                                                             ")
time.sleep(1)
print("     000       000        00              00         00              00      ")
time.sleep(1)
print("     000       000         00            00           00            00       ")
time.sleep(1)
print("     000       000          00          00             00          00        ")
time.sleep(1)
print("     0000000000000           00        00               00        00         ")
time.sleep(1)
print("     0000000000000            00      00                 00      00          ")
time.sleep(1)
print("     000       000             00    00                   00    00           ")
time.sleep(1)
print("     000       000              00  00                     00  00            ")
time.sleep(1)
print("     000       000                00                         00              ")
time.sleep(1)
print("                                                                             ")
print(" ")
time.sleep(1)
print("Er zijn meedere keuzes dus probeer alles zeker uit!")
print(" ")
time.sleep(1)
print("BELANGERIJK: De meeste vragen worden beantwoord met Y of N ( Yes or no ) gebruik hierbij altijd hoofdletters om bugs te verkomen.")
time.sleep(1)

while repeat[0] not in ("N"):
    time.sleep(5)
    os.system('cls')
    print("Mijn naam is Alyas, vandaag ben jij verantwoordelijk voor mijn keuzes. Jij moet mij helpen om naar Nederland te komen.")
    time.sleep(1)
    print(" ")
    print(" ")
    print(" ")
    time.sleep(1)
    print("Laten we beginnen bij het begin ik woon samen met mijn vrouw en zoon in Irak. We waren heel gelukkig, totdat er oorlog uitbrak.")
    print(" ")
    time.sleep(1)
    print("De rede dat wij willen vluchten is omdat wij een apart geloof hebben dat niet word geaccepteerd. Dus we zijn niet veilig.")
    print(" ")
    time.sleep(1)
    print("We willen zo snel mogelijk vertrekken maar het is wel belangrijk dat wij een plan maken.")
    time.sleep(1)
    print("Welke kant kunnen wij het beste op?")
    time.sleep(1)
    print("Keuzes: A: Via Turkije, B: Libanon, C: Vliegtuig ")
    time.sleep(1)
    w1v1 = input("Keuze: ")
    if w1v1 == "A":
        print("Via Turkije word het dan!")
        time.sleep(1)
        print(" ")
        time.sleep(1)
        print("Gaan we een vervoersmiddel gebruiken?")
        time.sleep(1)
        w1v2 = input("Y/N: ")
        if w1v2 == "Y":
            print("Oke dan!")
            time.sleep(1)
            print("Daar staat een vrachtwagen, ik ga hem vragen of wij mee mogen!")
            time.sleep(1)
            print(" ")
            time.sleep(1)
            print("De chauffeur zij ja en we mogen mee richting Turkije!")
            print(" ")
            time.sleep(1)
            print("De reis duurde een aantal uur maar we zijn aangekomen in Turkije.")
            print(" ")
            time.sleep(1)
            print("We zijn redelijk uitgeput en moeten ergens een tijdje rusten...")
            time.sleep(1)
        if w1v2 == "N":
            print("Dan maar te voet...")
            time.sleep(1)
            print(" ")
            time.sleep(1)
            print("Het lopen is enorm zwaar...")
            time.sleep(1)
            print(" ")
            print("Maar gelukkig konden we onderweg wat eten scoren.")
            print(" ")
            time.sleep(1)
            print("Na 15 dagen lopen zijn we aangekomen in Turkije")
            print(" ")
            time.sleep(1)
            print("We zijn uitgeput en moeten ergens een tijdje rusten...")
            time.sleep(1)

        print("We zijn op dit moment in het stadje Kalaba")
        print(" ")
        time.sleep(1)
        print("We konden hier nergens een rust plaats vinden dus zijn maar op straat gaan slapen...")
        print(" ")
        time.sleep(1)
        print("De volgende dag zijn we door gelopen naar het stadje Kırşehir, daar woont een nicht van mij dus we konden daar gelukkig een tijdje rusten.")
        print(" ")
        time.sleep(1)
        print("Na een aantal dagen te rusten wilde we weer verder, dus mijn nicht had ons afgezet bij de grens van Bulgarije.")
        print(" ")
        time.sleep(1)
        print("Gaan we vanaf hier weer een vervoersmiddel gebruiken?")
        print(" ")
        time.sleep(1)
        w1v3 = input("Y/N: ")
        if w1v3 == "Y":
            print(" ")
            print("We hebben ons laatste geld uitgegeven aan een busreis van 15 uur.")
            print(" ")
            time.sleep(1)
            print("Hiermee konden helemaal bij Praag komen! Eenmaal in Praag hebben we even uitgerust. Er was een vriendelijke motel eigenaar die ons een gratis nachtje gunde!")
            print(" ")
            time.sleep(1)
        if w1v3 == "N":
            print("Gaat lastig worden zonder vervoer... Maar gelukkig hebben we nu nog wel wat geld over.")
            print(" ")
            time.sleep(1)
            print("Ik heb het laatste geld gebruikt en we hebben kleine stukjes gelift en zijn vervolgens in Praag aangekomen")
            print(" ")
            time.sleep(1)
            print("Eenmaal in Praag hebben we even uitgerust. Er was een vriendelijke motel eigenaar die ons een gratis nachtje gunde!")
            time.sleep(1)
            break

        print("Het is vanaf Praag nog maar 850Km. Wij besloten om in Praag proberen wat geld te verdienen. We hebben hier een aantal klusjes gedaan voor verschillende mensen!")
        print(" ")
        time.sleep(1)
        print("We hebben genoeg geld bij elkaar gehaald om met de bus naar Duitsland te gaan!")
        print(" ")
        time.sleep(1)
        print("Vanaf Duitsland konden we zo naar Amsterdam!")
        print(" ")
        time.sleep(1)
        print("De reis verliep soepeltjes en we zijn veilig op eindbestemming gekomen.")
        print(" ")
        time.sleep(1)

    if w1v1 == "B":
        print("Via Libanon")
        print(" ")
        time.sleep(1)
        print("Kijken wat ons dit gaat brengen")
        print(" ")
        time.sleep(1)
        print("Gaan we een vervoersmiddel gebruiken?")
        w2v2 = input("Y/N: ")
        if w2v2 == "Y":
            print("Een vervoersmiddel it is.")
            print(" ")
            time.sleep(1)
            print("Libanon ligt naast Syrie, dat betekent dat we daar eerst doorheen moeten.")
            print(" ")
            time.sleep(1)
            print("Gelukkig gaat er een bus vanaf Syrie naar Libanon.")
            print(" ")
            time.sleep(1)
            print("Het was 5 uur lopen maar we zijn bij de bus gekomen")
            print(" ")
            time.sleep(1)
            print("Gelukkig ging de de reis met de bus goed!")
            time.sleep(1)
            print(" ")
        if w2v2 == "N":
            print("Geen vervoersmiddel?")
            print(" ")
            time.sleep(1)
            print("Het bespaart veel geld maar het is wel gevaarlijk.")
            print(" ")
            time.sleep(1)
            print("Nouja we hebben de fiets maar genomen richting libanon.")
            print(" ")
            time.sleep(1)
            print("Het was een gevaarlijke reis maar we hebben het gedaan.")
            print(" ")
            time.sleep(1)
            print("De reis duurde in totaal meer dan 2 dagen.")
            print(" ")
            time.sleep(1)
        
        print("Nouja de reden dat we naar Libanon zijn gegaan is zodat we met de boot kunnen.")
        print(" ")
        time.sleep(1)
        print("We hebben met een aantal andere vluchtelingen een bootje gehuurd.")
        print(" ")
        time.sleep(1)
        print("Deze zijn niet altijd even veilig maarja...")
        print(" ")
        time.sleep(1)
        print("Er zaten in totaal 15 mensen in de boot.")
        print(" ")
        time.sleep(1)
        print("Het was een verschikkelende tocht.")
        print(" ")
        time.sleep(1)
        print("Na dagen varen kwamen we aan in Griekenland aan.")
        print(" ")
        time.sleep(1)
        print("We hebben vanaf daar een vrachtwagen bestuurder omgekocht.")
        print(" ")
        time.sleep(1)
        print("Na een aantal uren varen werd de vrachtwagen stilgezet.")
        print(" ")
        time.sleep(1)
        print("Het was de griekse politie.")
        print(" ")
        time.sleep(1)
        print("We werden allemaal verplaats naar een vluchtelingenkamp in Griekenland.")
        print(" ")
        time.sleep(1)
        print("Wat moeten we nu? Gaan we weg hier?")
        w2v3 = input("Y/N: ")
        if w2v3 == "Y":
            print("Oke dan!")
            print(" ")
            time.sleep(1)
            print("We hebben het kamp verlaten en wilde verder naar Nederland.")
            print(" ")
            time.sleep(1)
            print("Het was nog ongeveer 500 uur lopen naar Nederland.")
            print(" ")
            time.sleep(1)
            print("Dus we hadden een andere manier nodig.")
            print(" ")
            time.sleep(1)
            print("We kunnen ook naar Bulgerije waar een neef van mij woont?")
            print(" ")
            time.sleep(1)
            print("Gaan we daar heen?")
            w2v4 = input("Y/N: ")
            if w2v4 == "Y":
                print("Op naar Bulgerije dan maar.")
                print(" ")
                time.sleep(1)
                print("Na een hele dag lopen waren we allemaal uitgeput.")
                print(" ")
                time.sleep(1)
                print("We wisten niet wat we moesten doen.")
                print(" ")
                time.sleep(1)
                print("We waren bij de grens van Bulgerije maar het was alsnog nog lang lopen...")
                print(" ")
                time.sleep(1)
                print("Dus we moesten wel een auto zoeken om te liften.")
                print(" ")
                time.sleep(1)
                print("Na 10 pogingen was er een familie die ons wel een stukje wilde meenemen.")
                print(" ")
                time.sleep(1)
                print("Ze hadden ons afgezet in de stad van mijn neef.")
                print(" ")
                time.sleep(1)
                print("Het was alsnog een stuk lopen maar we hebben het gehaald!")
                print(" ")
                time.sleep(1)
                print("Mijn neef ving ons op en we konden daar een tijdje blijven.")
                print(" ")
                time.sleep(1)
                print("Ik had wat werk voor mijn neef gedaan waardoor we wat extra geld hadden voor de reis.")
                print(" ")
                time.sleep(1)
                print("Na een maand had ik 900 euro bij elkaar.")
                print(" ")
                time.sleep(1)
                print("Vervolgens reed hij ons een stuk verder.")
                print(" ")
                time.sleep(1)
                print("Hij had ons afgezet bij de grens van Oosterijk.")
                print(" ")
                time.sleep(1)
                print("We hadden genoeg eten bij ons voor een aantal dagen.")
                print(" ")
                time.sleep(1)
                print("Dus we zijn maar door de bergen gaan lopen.")
                print(" ")
                time.sleep(1)
                print("Dit was enorm zwaar.")
                print(" ")
                time.sleep(1)
                print("Maar na een week lopen en klimmen zijn we door de bergen heengekomen.")
                print(" ")
                time.sleep(1)
                print("Voor alle wintersporters gaat er altijd een bus van Oosterijk naar Schiphol.")
                print(" ")
                time.sleep(1)
                print("We hadden genoeg geld dus we hebben die genomen.")
                print(" ")
                time.sleep(1)
                print("Na een lange reis waren we er eindelijk!")
                print(" ")
                time.sleep(1)
                print("We hebben ons ingeschreven als asielzoeker en we werden snel aangekomen.")
                print(" ")
                time.sleep(1)
                print("We zijn enorm dankbaar dat we nu in Nederland wonen!")
                print(" ")
                time.sleep(1)
                print("Het is je gelukt!")
                print(" ")
                time.sleep(1)
                print("Je hebt ervoor gezorgt dat deze familie in Nederland is gekomen.")
                print(" ")
                print(" ")
                time.sleep(1)
                print("Dit was het hele verhaal.")
                print(" ")
                time.sleep(1)
                print("Al was het gelukt via 1 weg probeer dan zeker nog even de andere uit!")
                print(" ")
                time.sleep(1)
                print("Wilt u het nog eens doen?")
                repeat = input("Y/N: ")
                time.sleep(1)
            if w2v4 == "N":
                print("Dan moeten we maar een andere manier zoeken...")
                print(" ")
                time.sleep(1)
                print("We hebben niet heel veel keus meer.")
                print(" ")
                time.sleep(1)
                print("We moeten maar gaan lopen en liften.")
                print(" ")
                time.sleep(1)
                print("Na uren lopen kwamen we aan bij een vrachtwagen parkeerplaats.")
                print(" ")
                time.sleep(1)
                print("We hebben meedere chauffeurs gevraagt of we mee mochten.")
                print(" ")
                time.sleep(1)
                print("Uiteindelijk wilde er één ons wel meenemen.")
                print(" ")
                time.sleep(1)
                print("Hij moest helemaal vanaf Griekenland naar Duitsland.")
                print(" ")
                time.sleep(1)
                print("Dus dat scheelt ons enorm!")
                print(" ")
                time.sleep(1)
                print("Na een week waren we eindelijk bij de bestemming.")
                print(" ")
                time.sleep(1)
                print("Duitsland!")
                print(" ")
                time.sleep(1)
                print("We voelde ons al een stuk veiliger.")
                print(" ")
                time.sleep(1)
                print("Maar onze reis eindigd hier nog niet.")
                print(" ")
                time.sleep(1)
                print("We hebben een heel stuk moeten lopen want we hadden geen geld.")
                print(" ")
                time.sleep(1)
                print("We waren helemaal op en we konden niet meer lopen.")
                print(" ")
                time.sleep(1)
                print("Dus we moesten maar zwartreizen.")
                print(" ")
                time.sleep(1)
                print("We hebben alleen een groot probleem al worden we gepakt.")
                print(" ")
                time.sleep(1)
                print("We hebben de hele reis bij de fietsenstalling gezeten en gelukkig kwam er niemand langs.")
                print(" ")
                time.sleep(1)
                print("We kwamen aan in Utrecht.")
                print(" ")
                time.sleep(1)
                print("We hebben ons ingeschreven als asielzoeker en we konden voor een tijdje ergens terecht.")
                print(" ")
                time.sleep(1)
                print("Toen wij aangenomen in Nederland waren hebben we familie opgezocht.")
                print(" ")
                time.sleep(1)
                print("Wij konden daar een tijdje wonen totdat ik een baan heb")
                print(" ")
                time.sleep(1)
                print("Ik hoop dat wij ons leven hier weer helemaal op kunnen pakken!")
                print(" ")
                time.sleep(1)
                print("Het is je gelukt!")
                print(" ")
                time.sleep(1)
                print("Je hebt ervoor gezorgt dat deze familie in Nederland is gekomen.")
                print(" ")
                time.sleep(1)
                print("Dit was het hele verhaal.")
                print(" ")
                print("Al was het gelukt via 1 weg probeer dan zeker nog even de andere uit!")
                print(" ")
                time.sleep(1)
                print("Wilt u het nog eens doen?")
                repeat = input("Y/N: ")
                
        if w2v3 == "N":
            print("Dan blijven we nog maar even hier...")
            print(" ")
            time.sleep(1)
            print("Het was een nare tijd.")
            print(" ")
            time.sleep(1)
            print("Het was een vies kamp en er was weinig eten.")
            print(" ")
            time.sleep(1)
            print("Het was zo vol het kon eigenlijk niet langer.")
            print(" ")
            print(" ")
            time.sleep(1)
            print("Mislukt! In het kamp werd het niet beter...")
            print(" ")
            time.sleep(1)
            print("We werden steeds oververplaats maar zijn nooit in Nederland terecht gekomen.")
            print(" ")
            time.sleep(1)
            print("Wilt u het nog eens proberen?")
            repeat = input("Y/N: ")
            
                
    
    if w1v1 == "C":
        print("Met het vliegtuig")
        print(" ")
        time.sleep(1)
        print("Het gaat lastig worden om Nederland in te komen...")
        print(" ")
        time.sleep(1)
        print("We hebben eerst meer geld nodig.")
        print(" ")
        time.sleep(1)
        print("Hoe gaan we dat doen?")
        print(" ")
        time.sleep(1)
        print("Zullen we naar het casino?")
        time.sleep(1)
        w1v2 = input("Y/N: ")
        if w1v2 == "Y":
            print("Oke dan!")
            print(" ")
            time.sleep(1)
            print("We hebben in totaal 150 euro...")
            print(" ")
            time.sleep(1)
            print("We hebben 600 euro nodig...")
            print(" ")
            time.sleep(1)
            print("Gaan we all in op rood of op zwart?")
            time.sleep(1)
            w1v3 = input("R/Z: ")
            if w1v3 == "R":
                print("YESS!")
                print(" ")
                time.sleep(1)
                print("We hebben het verdubbeld!")
                print(" ")
                time.sleep(1)
                print("We missen nog 300 euro...")
                print("  ")
                time.sleep(1)
                print("Als we nog eens alles inzetten op rood of zwart dan kunnen we 600 euro winnen.")
                print(" ")
                time.sleep(1)
                print("Kies nog eens tussen rood of zwart.")
            if w1v3 == "Z":
                print("YESS!")
                print(" ")
                time.sleep(1)
                print("We hebben het verdubbeld!")
                print(" ")
                time.sleep(1)
                print("We missen nog 300 euro...")
                print("  ")
                time.sleep(1)
                print("Als we nog eens alles inzetten op rood of zwart dan kunnen we 600 euro winnen.")
                print(" ")
                time.sleep(1)
                print("Kies nog eens tussen rood of zwart.")
                
                w1v4 = input("R/Z: ")
                if w1v4 == "R":
                    print("HET IS GELUKT!")
                    print(" ")
                    time.sleep(1)
                    print("We kunnen met het vluigtuig!")
                    print(" ")
                    time.sleep(1)
                    print("Alles verliep soepel en we zijn naar Nederland gekomen.")

                if w1v4 == "Z":
                    print("Helaas!")
                    print(" ")
                    time.sleep(1)
                    print("We zullen een andere manier moeten zoeken...")
                    time.sleep(1)
                    repeat = input("Wilt u terug naar het begin?(Y/N): ")
        if w1v2 == "N":
            print("Helaas...")
            print(" ")
            time.sleep(1)
            print("Zonder geld geen vluigtuig...")
            print(" ")
            time.sleep(1)
            print("Wilt u het nog eens proberen?")
            repeat = input("Y/N: ")
        print("Het is je gelukt!")
        print(" ")
        time.sleep(1)
        print("Je hebt ervoor gezorgt dat deze familie in Nederland is gekomen.")
        print(" ")
        print(" ")
        time.sleep(1)
        print("Dit was het hele verhaal.")
        print("Al was het gelukt via 1 weg probeer dan zeker nog even de andere uit!")
        print(" ")
        time.sleep(1)
        print("Wilt u het nog eens doen?")
        repeat = input("Y/N: ")
        
                    
                    
        



            
            
            
    
    


